require_relative '../node_modules/react-native/scripts/react_native_pods'


platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'ortakHesap' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
